### ISSUE TITLE
 Error: Getter not found: 'HttpRequest' after adding 0.8.0 version

### ISSUE THREAD

**Issue by laksh97** [srawlins/timezone#116]
flutter/.pub-cache/hosted/pub.dartlang.org/timezone-0.8.0/lib/browser.dart:47:10: Error: Getter not found: 'HttpRequest'.
  return HttpRequest.request(path,
         ^^^^^^^^^^^
Unhandled exception:
FileSystemException(uri=org-dartlang-untranslatable-uri:dart%3Ahtml; message=StandardFileSystem only supports file:* and data:* URIs)
#0      StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system.dart:34:7)
#1      asFileUri (package:vm/kernel_front_end.dart:614:37)
#2      writeDepfile (package:vm/kernel_front_end.dart:754:21)
<asynchronous suspension>
#3      FrontendCompiler.compile (package:frontend_server/frontend_server.dart:570:9)
<asynchronous suspension>
#4      starter (package:flutter_frontend_server/server.dart:85:12)

Please help.

**Comment by laksh97** [comment]
The issue has been resolved. Please check that the below file is imported for the package.

import 'package:timezone/data/latest.dart' as tz;
