### ISSUE TITLE
Unsupported operation: Isolate.resolvePackageUri

### ISSUE THREAD

**Issue by MichaelHipp** [srawlins/timezone#52]
When calling `await initializeTimeZone();` I'm getting this exception. Any suggestions?
```
E/flutter ( 3330): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Unsupported operation: Isolate.resolvePackageUri
E/flutter ( 3330): #0      initializeTimeZone.<anonymous closure> (package:timezone/standalone.dart:81:5)
E/flutter ( 3330): #1      _rootRunUnary (dart:async/zone.dart:1134:38)
E/flutter ( 3330): #2      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
E/flutter ( 3330): #3      _FutureListener.handleError (dart:async/future_impl.dart:158:20)
E/flutter ( 3330): #4      Future._propagateToListeners.handleError (dart:async/future_impl.dart:694:47)
E/flutter ( 3330): #5      Future._propagateToListeners (dart:async/future_impl.dart:715:24)
E/flutter ( 3330): #6      Future._completeError (dart:async/future_impl.dart:534:5)
E/flutter ( 3330): #7      Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:582:7)
E/flutter ( 3330): #8      _rootRun (dart:async/zone.dart:1126:13)
E/flutter ( 3330): #9      _CustomZone.run (dart:async/zone.dart:1023:19)
E/flutter ( 3330): #10     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
E/flutter ( 3330): #11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
E/flutter ( 3330): #12     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
E/flutter ( 3330): #13     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
```

**Comment by srawlins** [comment]
Note: the user appears to be running Flutter here.

I think `initializeTimeZone` will not work in Flutter. Have you tried [`initializeTimeZones`](https://github.com/srawlins/timezone#initialization-from-dart-library) instead?

**Comment by MichaelHipp** [comment]
Thanks. No I have not tried `initializeTimeZones` with-an-s as I never noticed those were two separate calls. I'll give it a shot.

Methinks one function or the other needs to be renamed to something a bit more distinct.

**Comment by MichaelHipp** [comment]
This appears to work. Thanks for that.
